[update to 3.1.4] lib/tpm2_options: fix potential dereference of NULL return value
Javier Martinez Canillas (1):
      options: fix broken -T option when passing additional arguments

Jerry Snitselaar (1):
      tpm2_create: remove non-existent flag from examples

Jonas Witschel (5):
      configure: ensure POSIX compatibility
      test/unit: fix undefined reference to external variable
      build: use LDADD for unit tests
      build: update for ax_code_coverage.m4 version 2019.01.06
      build: install aclocal files

Joshua Lock (4):
      tpm2_rsaencrypt: fix example in man page
      lib/tpm2_options: fix potential dereference of NULL return value
      Update CHANGELOG for 3.1.4-rc0
      CHANGELOG: update for 3.1.4 release

Pierre Bourdon (1):
      test_tpm2_alg_util: fix compatibility with tss 2.2.0+

William Roberts (2):
      tpm2_getmanufc: fix OSSL build warnings
      options: fix broken -T option

Key imported:
--list-packet:
# off=0 ctb=99 tag=6 hlen=3 plen=525
:public key packet:
	version 4, algo 1, created 1528463741, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 49BCAE5443FFFC34
# off=528 ctb=b4 tag=13 hlen=2 plen=37
:user ID packet: "Joshua Lock <joshua.g.lock@intel.com>"
# off=567 ctb=89 tag=2 hlen=3 plen=574
:signature packet: algo 1, keyid 49BCAE5443FFFC34

--fingerprint:
pub   rsa4096 2018-06-08 [SC] [expires: 2021-06-07]
      5BEC 526C E3A6 1CAF 07E7  A7DA 49BC AE54 43FF FC34
uid           [ unknown] Joshua Lock <joshua.g.lock@intel.com>
sub   rsa4096 2018-06-08 [E] [expires: 2021-06-07]